services:

  postgres:
    image: postgres:16
    container_name: cms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1409
      POSTGRES_DB: clinic-mvc
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cms_redis
    ports:
      - "6380:6379"
    restart: always

  minio:
    image: minio/minio
    container_name: cms_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_SERVER_URL: http://minio:9000
    volumes:
      - minio_data:/data
    ports:
      - "9005:9000"
      - "9006:9001"

  backend:
    build: ./backend-mvc
    container_name: cms_backend
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - lucene_data:/lucene

  frontend:
    build: ./frontend
    container_name: cms_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"


volumes:
  pg_data:
  minio_data:
  lucene_data:
