services:

  postgres:
    image: postgres:16
    container_name: cms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1409
      POSTGRES_DB: clinic-mvc
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cms_redis
    ports:
      - "6380:6379"
    restart: always

  minio:
    image: minio/minio
    container_name: cms_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_SERVER_URL: http://minio:9000
    volumes:
      - minio_data:/data
    ports:
      - "9005:9000"
      - "9006:9001"

  backend:
    build: ./backend-mvc
    container_name: cms_backend
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - lucene_data:/lucene

  frontend:
    build: ./frontend
    container_name: cms_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

  chat_mongodb:
    image: mongo:7
    container_name: chat_mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1409
    volumes:
      - mongo_data:/data/db

  chatbackend:
    build: ./chat-backend
    container_name: cms_chat_backend
    depends_on:
      - chat_mongodb
      - minio
    ports:
      - "9888:9888"
  
  chatfrontend:
    build: ./chat-frontend
    container_name: cms_chat_frontend
    depends_on:
      - chatbackend
    ports:
      - "5000:80"

volumes:
  pg_data:
  minio_data:
  lucene_data:
  mongo_data:


# To start the services, run: docker compose up -d
# To stop the services, run: docker compose down
# To recomplile the backend or frontend, use: docker compose build <service_name>